version: '3.7'

services:
  server:
    build:
      context: ./server
    container_name: server
    networks:
      custom_network:
        ipv4_address: 172.19.1.3
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    environment:
      - container=docker
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    privileged: true

  client:
    build:
      context: ./client
    container_name: client
    networks:
      custom_network:
        ipv4_address: 172.19.1.2
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    environment:
      - container=docker
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    privileged: true

  attacker:
    build:
      context: ./attacker
    container_name: attacker
    networks:
      custom_network:
        ipv4_address: 172.19.1.4
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    environment:
      - container=docker
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    privileged: true

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
